"""add i databas

Revision ID: 51e3ef176783
Revises: 
Create Date: 2025-06-02 16:21:02.037077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e3ef176783'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnummer', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_personnummer'), 'customers', ['personnummer'], unique=True)
    op.create_table('skipped_transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_sek', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sender_account', sa.String(), nullable=False),
    sa.Column('receiver_account', sa.String(), nullable=False),
    sa.Column('sender_country', sa.String(), nullable=False),
    sa.Column('sender_municipality', sa.String(), nullable=False),
    sa.Column('receiver_country', sa.String(), nullable=False),
    sa.Column('receiver_municipality', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_account', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_sek', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('receiver_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_country', sa.String(), nullable=False),
    sa.Column('sender_municipality', sa.String(), nullable=False),
    sa.Column('receiver_country', sa.String(), nullable=False),
    sa.Column('receiver_municipality', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('skipped_transactions')
    op.drop_index(op.f('ix_customers_personnummer'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
